{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "clawhermes-ai.fullname" . }}
  labels:
    {{- include "clawhermes-ai.labels" . | nindent 4 }}
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: {{ include "clawhermes-ai.name" . }}
  endpoints:
    - port: http
      path: {{ .Values.prometheus.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scheme: http
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
{{- end }}